### ISSUE TITLE
Invalid argument supplied for foreach

### ISSUE THREAD

**Issue by anuj9196** [dereuromark/cakephp-meta#3]
As per your configuration documentation, I'm adding meta tags from within action

    public function view($title = null)
    {
        $contentPage = $this->ContentPages->find()
          ->where(['Categories.title LIKE' => 'Services', 'ContentPages.title LIKE' => $title, 'ContentPages.status' => 0])
          ->contain(['Categories'])
          ->first();

        $_meta = [
            'title' => $contentPage->title,
            'keywords' => $contentPage->meta_keyword,
            'description' => $contentPage->meta_description,
            'author' => 'DigiTechXPro'
        ];
     
        $this->set('contentPage', $contentPage);
        $this->set(compact('_meta'));
        $this->set('_serialize', ['contentPages']);
    }

But this is producing error
   ` Warning (2): Invalid argument supplied for foreach() [ROOT/vendor/dereuromark/cakephp-meta/src/View/Helper/MetaHelper.php, line 326]`

> Edit 2

on `debug($_meta)` in the action, it gives

    [
	    'title' => 'SEO Services',
	    'keywords' => 'hello, world',
	    'description' => 'hello',
	    'author' => 'DigiTechXPro'
    ]

**Comment by dereuromark** [comment]
Is `$contentPage->meta_keyword` an array as it here should be? array[de=>something] etc.
What is the content at this point?

**Comment by dereuromark** [comment]
I will try to add a test for string and default lang then.

**Comment by dereuromark** [comment]
Please confirm that https://github.com/dereuromark/cakephp-meta/commit/71f805bb01732f985fc1a73e5a90c8af50980350 solves it for you.

**Comment by anuj9196** [comment]
Check ```Edit 2``` The value of `$contentPage->meta_keyword` is string not an array

**Comment by anuj9196** [comment]
Adding meta like this solved the problem

        $_meta = [
            'title' => $contentPage->title,
            'keywords' => ['en' => $contentPage->meta_keyword],
            'description' => ['en' => $contentPage->meta_description],
            'author' => 'DigiTechXPro'
        ];

**Comment by dereuromark** [comment]
I am sry, I only fixed description instead of keywords in the commit above.
Now with https://github.com/dereuromark/cakephp-meta/commit/b9c3092e05283c95cd5c37185f66ae3ba76a8bd6 both should be fine as strings as well.
Thanks a lot for helping out and reporting it.
