### ISSUE TITLE
Adding metadata in default.ctp overriding metadata of controller->action

### ISSUE THREAD

**Issue by anuj9196** [dereuromark/cakephp-meta#6]
* [x] Bug

* CakePHP : 3.x

### What I did
I am adding meta data from action of controller like

    $_meta = [
          'title' => 'title for action'
    ];
    $this->set(compact('_meta'));

and in default.ctp 

    $this->Meta->title(' : Company Name');
    $this->Meta->out();

### Expected Output

    title for action : Company Name

**Comment by dereuromark** [comment]
It does not append, it overwrites.
We could add a flag to append, instead. 
But this would maybe not work for all attributes?

Just do `$this->Meta->title($this->Meta->title() . ' : Company Name');`
